# Generated by Django 4.2.4 on 2023-09-04 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_followers_alter_profile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="hashtag",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ("id",)},
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="HashTag",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
